

# Further information

## Case definitions

### Suspected COVID-19

A. Person who meets the clinical AND epidemiological criteria:

-   Clinical criteria:

    Acute onset of fever AND cough; OR,

    Acute onset of ANY THREE OR MORE of the following signs or symptoms:

    -   fever,cough

    -   general weakness/fatigue

    -   headache

    -   myalgia

    -   sore throat

    -   coryza

    -   dyspnoea

    -   anorexia/nausea/vomiting

    -   diarrhoea

    -   altered mental status.

-   Epidemiological criteria

    -   Residing (or working) in an area with high risk of transmission of the virus: for example, closed residential settings and humanitarian settings, such as camp and camp-like settings for displaced persons, any time within the 14 days prior to symptom onset;

        OR,

    -   Residing in or travel to an area with community transmission anytime within the 14 days prior to symptom onset;

        OR,

    -   Working in health setting, including within health facilities and within households, anytime within the 14 days prior to symptom onset.

B. A patient with severe acute respiratory illness (SARI: acute respiratory infection with history of fever or measured fever of ≥ 38 C°; and cough; with onset within the last 10 days; and who requires hospitalization)

### Probable COVID-19

Definition A: A patient who meets clinical criteria above AND is a contact of a probable or confirmed case, or epidemiologically linked to a cluster of cases which has had at least one confirmed case identified within that cluster.

Definition B: A suspected case (described above) with chest imaging showing findings suggestive of COVID-19 disease.

Definition C: A person with recent onset of anosmia (loss of smell) or ageusia (loss of taste)in the absence of any other identified cause.

Definition D: Death, not otherwise explained, in an adult with respiratory distress preceding death AND who was a contact of a probable or confirmed case or epidemiologically linked to a cluster which has had at least one confirmed case identified within that cluster.

### Confirmed COVID-19

A person with laboratory confirmation of COVID-19 infection, irrespective of clinical signs and symptoms.

\newpage

